version: "3.9"

services:
  backend:
    build: .
    container_name: mpstme-pics-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/mpstme_pics
      JWT_SECRET: your-secret
      S3_BUCKET_NAME: your-bucket-name
      AWS_ACCESS_KEY_ID: your-access-key
      AWS_SECRET_ACCESS_KEY: your-secret-access
      UPLOAD_MAX_MB: 10
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: mpstme-pics-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mpstme_pics
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
