services:
    backend:
        image: ghcr.io/kartikjain14/mpstme.pics:latest
        container_name: mpstme-pics-backend
        restart: unless-stopped
        ports:
            - "3001:3001"
        depends_on:
            - db
        env_file:
            - ./backend/.env.prod
        volumes:
            - .:/app
        command: ["sh", "-c", "npx drizzle-kit migrate && npm run start"]

    db:
        image: bitnami/postgresql
        container_name: mpstme-pics-db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mpstme_pics
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: bitnami/redis:latest
        container_name: mpstme-pics-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
    
volumes:
    postgres_data:
    redis_data:
