version: "3.9"

services:
    backend:
        image: ghcr.io/kartikjain14/mpstme.pics:latest
        container_name: mpstme-pics-backend
        restart: unless-stopped
        ports:
            - "3001:3001"
        depends_on:
            - db
        env_file:
            - ./backend/.env.prod
        volumes:
            - .:/app

    db:
        image: postgres:15
        container_name: mpstme-pics-db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mpstme_pics
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
