import type { User, Club, Album, Photo, AuditLog } from "./types"

export const dummyUsers: User[] = [
  {
    id: "user-1",
    email: "superadmin@mpstme.edu",
    role: "superadmin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "user-2",
    email: "admin@csi.edu",
    role: "clubadmin",
    clubId: "club-1",
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-02T00:00:00Z",
  },
  {
    id: "user-3",
    email: "admin@ieee.edu",
    role: "clubadmin",
    clubId: "club-2",
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-03T00:00:00Z",
  },
  {
    id: "user-4",
    email: "admin@acm.edu",
    role: "clubadmin",
    clubId: "club-3",
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-04T00:00:00Z",
  },
  {
    id: "user-5",
    email: "admin@robotics.edu",
    role: "clubadmin",
    clubId: "club-4",
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "user-6",
    email: "admin@photography.edu",
    role: "clubadmin",
    clubId: "club-5",
    createdAt: "2024-01-06T00:00:00Z",
    updatedAt: "2024-01-06T00:00:00Z",
  },
  {
    id: "user-7",
    email: "admin@drama.edu",
    role: "clubadmin",
    clubId: "club-6",
    createdAt: "2024-01-07T00:00:00Z",
    updatedAt: "2024-01-07T00:00:00Z",
  },
]

export const dummyClubs: Club[] = [
  {
    id: "club-1",
    name: "Computer Society of India",
    slug: "csi",
    logo: "CSI",
    bio: "The Computer Society of India (CSI) student chapter focuses on advancing computer science education and fostering innovation in technology. We organize workshops, hackathons, and technical seminars to bridge the gap between academic learning and industry requirements.",
    quota: 5000, // 5GB
    quotaUsed: 1247, // ~1.2GB used
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "club-2",
    name: "IEEE Student Branch",
    slug: "ieee",
    logo: "IEEE",
    bio: "IEEE Student Branch promoting electrical and electronics engineering excellence through workshops, technical events, and industry collaborations. We aim to advance technology for humanity.",
    quota: 3000, // 3GB
    quotaUsed: 892,
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "club-3",
    name: "ACM Student Chapter",
    slug: "acm",
    logo: "ACM",
    bio: "ACM Student Chapter dedicated to advancing computing as a science and profession. We host programming competitions, research seminars, and career development workshops.",
    quota: 2000, // 2GB
    quotaUsed: 456,
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "club-4",
    name: "Robotics Club",
    slug: "robotics",
    logo: "ROB",
    bio: "Robotics Club focused on automation, artificial intelligence, and mechatronics. We build robots, participate in competitions, and explore the future of autonomous systems.",
    quota: 4000, // 4GB
    quotaUsed: 1876,
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "club-5",
    name: "Photography Club",
    slug: "photography",
    logo: "PHOTO",
    bio: "Photography Club dedicated to visual arts and storytelling through images. We organize photo walks, exhibitions, and workshops on various photography techniques and post-processing.",
    quota: 8000, // 8GB
    quotaUsed: 3456,
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "club-6",
    name: "Drama Society",
    slug: "drama",
    logo: "DRAMA",
    bio: "Drama Society bringing stories to life through theatre and performing arts. We produce plays, organize acting workshops, and celebrate the rich tradition of dramatic arts.",
    quota: 2500, // 2.5GB
    quotaUsed: 789,
    createdAt: "2024-01-06T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "club-7",
    name: "Music Society",
    slug: "music",
    logo: "MUSIC",
    bio: "Music Society harmonizing talents and celebrating musical diversity. We organize concerts, music competitions, and provide a platform for budding musicians to showcase their skills.",
    quota: 3500, // 3.5GB
    quotaUsed: 1234,
    createdAt: "2024-01-07T00:00:00Z",
    updatedAt: "2024-03-05T00:00:00Z",
  },
  {
    id: "club-8",
    name: "Literary Society",
    slug: "literary",
    logo: "LIT",
    bio: "Literary Society fostering love for literature, creative writing, and public speaking. We host poetry sessions, book discussions, and writing workshops.",
    quota: 1500, // 1.5GB
    quotaUsed: 234,
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-02-28T00:00:00Z",
  },
]

export const dummyAlbums: Album[] = [
  // CSI Albums
  {
    id: "album-1",
    clubId: "club-1",
    name: "TechFest 2024",
    slug: "techfest-2024",
    description:
      "Annual technology festival showcasing innovation and creativity from students across various departments",
    isPublic: true,
    photoCount: 45,
    coverImage: "/placeholder.svg?height=200&width=300&text=TechFest",
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "album-2",
    clubId: "club-1",
    name: "AI Workshop Series",
    slug: "ai-workshop-series",
    description:
      "Hands-on artificial intelligence workshops covering machine learning, deep learning, and neural networks",
    isPublic: true,
    photoCount: 28,
    coverImage: "/placeholder.svg?height=200&width=300&text=AI+Workshop",
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "album-3",
    clubId: "club-1",
    name: "Hackathon 2024",
    slug: "hackathon-2024",
    description: "24-hour coding marathon where teams build innovative solutions to real-world problems",
    isPublic: true,
    photoCount: 67,
    coverImage: "/placeholder.svg?height=200&width=300&text=Hackathon",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "album-4",
    clubId: "club-1",
    name: "Internal Meeting",
    slug: "internal-meeting",
    description: "Private club meeting and planning session",
    isPublic: false,
    photoCount: 12,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // IEEE Albums
  {
    id: "album-5",
    clubId: "club-2",
    name: "Electronics Expo",
    slug: "electronics-expo",
    description: "Annual electronics exhibition showcasing student projects and industry innovations",
    isPublic: true,
    photoCount: 52,
    coverImage: "/placeholder.svg?height=200&width=300&text=Electronics",
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "album-6",
    clubId: "club-2",
    name: "Circuit Design Workshop",
    slug: "circuit-design-workshop",
    description: "Hands-on workshop on PCB design and circuit simulation",
    isPublic: true,
    photoCount: 34,
    coverImage: "/placeholder.svg?height=200&width=300&text=Circuit",
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
  },
  {
    id: "album-7",
    clubId: "club-2",
    name: "Industry Visit",
    slug: "industry-visit",
    description: "Educational visit to leading electronics manufacturing company",
    isPublic: false,
    photoCount: 23,
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },

  // ACM Albums
  {
    id: "album-8",
    clubId: "club-3",
    name: "Programming Contest",
    slug: "programming-contest",
    description: "Inter-college programming competition with algorithmic challenges",
    isPublic: true,
    photoCount: 41,
    coverImage: "/placeholder.svg?height=200&width=300&text=Programming",
    createdAt: "2024-02-05T00:00:00Z",
    updatedAt: "2024-02-05T00:00:00Z",
  },
  {
    id: "album-9",
    clubId: "club-3",
    name: "Open Source Day",
    slug: "open-source-day",
    description: "Celebrating open source software and encouraging student contributions",
    isPublic: true,
    photoCount: 29,
    coverImage: "/placeholder.svg?height=200&width=300&text=OpenSource",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },

  // Robotics Albums
  {
    id: "album-10",
    clubId: "club-4",
    name: "RoboWars 2024",
    slug: "robowars-2024",
    description: "Annual robot fighting competition with custom-built combat robots",
    isPublic: true,
    photoCount: 78,
    coverImage: "/placeholder.svg?height=200&width=300&text=RoboWars",
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "album-11",
    clubId: "club-4",
    name: "Drone Workshop",
    slug: "drone-workshop",
    description: "Building and programming autonomous drones for various applications",
    isPublic: true,
    photoCount: 36,
    coverImage: "/placeholder.svg?height=200&width=300&text=Drone",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "album-12",
    clubId: "club-4",
    name: "AI Robot Demo",
    slug: "ai-robot-demo",
    description: "Demonstration of AI-powered robots and machine learning applications",
    isPublic: true,
    photoCount: 44,
    coverImage: "/placeholder.svg?height=200&width=300&text=AI+Robot",
    createdAt: "2024-01-30T00:00:00Z",
    updatedAt: "2024-01-30T00:00:00Z",
  },

  // Photography Albums
  {
    id: "album-13",
    clubId: "club-5",
    name: "Nature Photography Exhibition",
    slug: "nature-photography-exhibition",
    description: "Stunning collection of nature photographs by club members",
    isPublic: true,
    photoCount: 89,
    coverImage: "/placeholder.svg?height=200&width=300&text=Nature",
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "album-14",
    clubId: "club-5",
    name: "Portrait Workshop",
    slug: "portrait-workshop",
    description: "Learning the art of portrait photography with professional techniques",
    isPublic: true,
    photoCount: 56,
    coverImage: "/placeholder.svg?height=200&width=300&text=Portrait",
    createdAt: "2024-02-25T00:00:00Z",
    updatedAt: "2024-02-25T00:00:00Z",
  },
  {
    id: "album-15",
    clubId: "club-5",
    name: "Street Photography Walk",
    slug: "street-photography-walk",
    description: "Capturing life and culture through candid street photography",
    isPublic: true,
    photoCount: 73,
    coverImage: "/placeholder.svg?height=200&width=300&text=Street",
    createdAt: "2024-01-18T00:00:00Z",
    updatedAt: "2024-01-18T00:00:00Z",
  },

  // Drama Society Albums
  {
    id: "album-16",
    clubId: "club-6",
    name: "Shakespeare Festival",
    slug: "shakespeare-festival",
    description: "Annual celebration of Shakespeare's works with multiple play performances",
    isPublic: true,
    photoCount: 62,
    coverImage: "/placeholder.svg?height=200&width=300&text=Shakespeare",
    createdAt: "2024-02-15T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "album-17",
    clubId: "club-6",
    name: "Improv Night",
    slug: "improv-night",
    description: "Spontaneous comedy and drama performances with audience participation",
    isPublic: true,
    photoCount: 38,
    coverImage: "/placeholder.svg?height=200&width=300&text=Improv",
    createdAt: "2024-01-28T00:00:00Z",
    updatedAt: "2024-01-28T00:00:00Z",
  },
]

export const dummyPhotos: Photo[] = [
  // TechFest 2024 Photos
  ...Array.from({ length: 45 }, (_, i) => ({
    id: `photo-techfest-${i + 1}`,
    albumId: "album-1",
    clubId: "club-1",
    filename: `techfest-${String(i + 1).padStart(3, "0")}.jpg`,
    originalName: `IMG_${String(i + 1).padStart(4, "0")}.jpg`,
    size: Math.floor(Math.random() * 3000000) + 1000000, // 1-4MB
    mimeType: "image/jpeg",
    isPublic: true,
    caption: `TechFest 2024 - ${["Opening ceremony", "Innovation showcase", "Student presentations", "Tech demos", "Award ceremony", "Networking session", "Workshop session", "Panel discussion"][i % 8]}`,
    uploadedAt: new Date(2024, 2, 15, 10 + Math.floor(i / 6), (i * 10) % 60).toISOString(),
  })),

  // AI Workshop Photos
  ...Array.from({ length: 28 }, (_, i) => ({
    id: `photo-ai-${i + 1}`,
    albumId: "album-2",
    clubId: "club-1",
    filename: `ai-workshop-${String(i + 1).padStart(3, "0")}.jpg`,
    originalName: `AI_${String(i + 1).padStart(3, "0")}.jpg`,
    size: Math.floor(Math.random() * 2500000) + 800000,
    mimeType: "image/jpeg",
    isPublic: true,
    caption: `AI Workshop - ${["Hands-on coding", "Neural network demo", "Machine learning basics", "Deep learning session", "Q&A session"][i % 5]}`,
    uploadedAt: new Date(2024, 1, 20, 14 + Math.floor(i / 4), (i * 15) % 60).toISOString(),
  })),

  // Hackathon Photos
  ...Array.from({ length: 67 }, (_, i) => ({
    id: `photo-hack-${i + 1}`,
    albumId: "album-3",
    clubId: "club-1",
    filename: `hackathon-${String(i + 1).padStart(3, "0")}.jpg`,
    originalName: `HACK_${String(i + 1).padStart(3, "0")}.jpg`,
    size: Math.floor(Math.random() * 3500000) + 1200000,
    mimeType: "image/jpeg",
    isPublic: true,
    caption: `Hackathon 2024 - ${["Team collaboration", "Coding session", "Brainstorming", "Presentation prep", "Final pitches", "Judging panel", "Winner announcement"][i % 7]}`,
    uploadedAt: new Date(2024, 0, 10, 9 + Math.floor(i / 8), (i * 8) % 60).toISOString(),
  })),

  // Electronics Expo Photos
  ...Array.from({ length: 52 }, (_, i) => ({
    id: `photo-electronics-${i + 1}`,
    albumId: "album-5",
    clubId: "club-2",
    filename: `electronics-${String(i + 1).padStart(3, "0")}.jpg`,
    originalName: `ELEC_${String(i + 1).padStart(3, "0")}.jpg`,
    size: Math.floor(Math.random() * 2800000) + 900000,
    mimeType: "image/jpeg",
    isPublic: true,
    caption: `Electronics Expo - ${["Project displays", "Circuit demonstrations", "Student innovations", "Industry exhibits", "Technical discussions"][i % 5]}`,
    uploadedAt: new Date(2024, 1, 10, 10 + Math.floor(i / 6), (i * 12) % 60).toISOString(),
  })),

  // RoboWars Photos
  ...Array.from({ length: 78 }, (_, i) => ({
    id: `photo-robowars-${i + 1}`,
    albumId: "album-10",
    clubId: "club-4",
    filename: `robowars-${String(i + 1).padStart(3, "0")}.jpg`,
    originalName: `ROBO_${String(i + 1).padStart(3, "0")}.jpg`,
    size: Math.floor(Math.random() * 4000000) + 1500000,
    mimeType: "image/jpeg",
    isPublic: true,
    caption: `RoboWars 2024 - ${["Robot battles", "Team preparations", "Arena action", "Crowd reactions", "Victory celebrations", "Technical repairs"][i % 6]}`,
    uploadedAt: new Date(2024, 2, 10, 15 + Math.floor(i / 10), (i * 7) % 60).toISOString(),
  })),

  // Nature Photography Photos
  ...Array.from({ length: 89 }, (_, i) => ({
    id: `photo-nature-${i + 1}`,
    albumId: "album-13",
    clubId: "club-5",
    filename: `nature-${String(i + 1).padStart(3, "0")}.jpg`,
    originalName: `NATURE_${String(i + 1).padStart(3, "0")}.jpg`,
    size: Math.floor(Math.random() * 5000000) + 2000000,
    mimeType: "image/jpeg",
    isPublic: true,
    caption: `Nature Photography - ${["Landscape beauty", "Wildlife capture", "Macro photography", "Sunset moments", "Forest scenes", "Water reflections", "Mountain views"][i % 7]}`,
    uploadedAt: new Date(2024, 2, 20, 8 + Math.floor(i / 12), (i * 6) % 60).toISOString(),
  })),

  // Private photos for internal meetings
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `photo-meeting-${i + 1}`,
    albumId: "album-4",
    clubId: "club-1",
    filename: `meeting-${String(i + 1).padStart(3, "0")}.jpg`,
    originalName: `MEET_${String(i + 1).padStart(3, "0")}.jpg`,
    size: Math.floor(Math.random() * 1500000) + 500000,
    mimeType: "image/jpeg",
    isPublic: false,
    caption: `Internal Meeting - ${["Planning session", "Team discussion", "Strategy meeting", "Budget review"][i % 4]}`,
    uploadedAt: new Date(2024, 0, 15, 14 + Math.floor(i / 3), (i * 20) % 60).toISOString(),
  })),
]

export const dummyAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    actor: "admin@csi.edu",
    action: "CREATE_ALBUM",
    target: "album",
    targetId: "album-1",
    metadata: { albumName: "TechFest 2024" },
    timestamp: "2024-03-15T00:00:00Z",
  },
  {
    id: "log-2",
    actor: "admin@csi.edu",
    action: "UPLOAD_PHOTOS",
    target: "album",
    targetId: "album-1",
    metadata: { photoCount: 45 },
    timestamp: "2024-03-15T10:00:00Z",
  },
  {
    id: "log-3",
    actor: "superadmin@mpstme.edu",
    action: "CREATE_CLUB",
    target: "club",
    targetId: "club-1",
    metadata: { clubName: "Computer Society of India" },
    timestamp: "2024-01-01T00:00:00Z",
  },
  {
    id: "log-4",
    actor: "admin@ieee.edu",
    action: "CREATE_ALBUM",
    target: "album",
    targetId: "album-5",
    metadata: { albumName: "Electronics Expo" },
    timestamp: "2024-02-10T00:00:00Z",
  },
  {
    id: "log-5",
    actor: "admin@robotics.edu",
    action: "UPLOAD_PHOTOS",
    target: "album",
    targetId: "album-10",
    metadata: { photoCount: 78 },
    timestamp: "2024-03-10T15:00:00Z",
  },
  {
    id: "log-6",
    actor: "admin@photography.edu",
    action: "PUBLISH_ALBUM",
    target: "album",
    targetId: "album-13",
    metadata: { albumName: "Nature Photography Exhibition" },
    timestamp: "2024-03-20T08:00:00Z",
  },
  {
    id: "log-7",
    actor: "superadmin@mpstme.edu",
    action: "CREATE_USER",
    target: "user",
    targetId: "user-5",
    metadata: { email: "admin@robotics.edu", role: "clubadmin" },
    timestamp: "2024-01-05T00:00:00Z",
  },
  {
    id: "log-8",
    actor: "admin@acm.edu",
    action: "DELETE_PHOTO",
    target: "photo",
    targetId: "photo-deleted-1",
    metadata: { reason: "Duplicate image" },
    timestamp: "2024-02-05T16:30:00Z",
  },
  {
    id: "log-9",
    actor: "admin@drama.edu",
    action: "UPDATE_ALBUM",
    target: "album",
    targetId: "album-16",
    metadata: { changes: { isPublic: true } },
    timestamp: "2024-02-15T12:00:00Z",
  },
  {
    id: "log-10",
    actor: "superadmin@mpstme.edu",
    action: "UPDATE_CLUB_QUOTA",
    target: "club",
    targetId: "club-5",
    metadata: { oldQuota: 6000, newQuota: 8000 },
    timestamp: "2024-03-01T09:00:00Z",
  },
]
